version: 2.1
orbs:
  node: circleci/node@4.0.0

jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run: yarn install --immutable
      - run: yarn test

workflows:
  node-tests:
    jobs:
      - build
