# Generated by Django 3.1 on 2020-09-28 12:38

from django.db import migrations

def ready_up(apps, migrations):
    for room in apps.get_model('server', 'room').objects.all():
        if type(room.state['ready']) == list:
            print('converting ready to list for', room.name)
            room.state['ready'] = {str(k): 'random' for k in room.state['ready']}
            room.save()


def ready_down(apps, migrations):
    for room in apps.get_model('server', 'room').objects.all():
        if type(room.state['ready']) == dict:
            print('converting ready to dict for', room.name)
            room.state['ready'] = [int(k) for k in room.state['ready'].keys()]
            room.save()



class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200928_1234'),
    ]

    operations = [
        migrations.RunPython(ready_up, ready_down)
    ]
