# Generated by Django 3.1 on 2020-10-10 21:11

from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200928_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('state', models.JSONField(default=server.models.Game.default_state)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.room')),
            ],
        ),
    ]
